"""Run the release audits.

Dispatcher + legal-skeleton writer. Does two things:
1. Lists the four expert audit agents (genericity, GDPR, text-classifier, legal) to be dispatched in
   parallel as Opus AI agents in-session. The audits themselves are run by the AI agents; this script
   does not auto-pass or auto-fail them.
2. Writes audit/legal_report.md (a skeleton that the legal-lawyer audit agent fills in). The file is
   gitignored (runtime artifact).

The release gate is: a human/agent confirms all four dispatched audits PASS after reviewing their
output. This script is the dispatch orchestrator, not an automated pass/fail checker.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

AGENT_AUDITS = [
    "audit/genericity_audit.md",
    "audit/gdpr_audit.md",
    "audit/text_classifier_audit.md",
    "audit/legal_lawyer_agent.md",
]

LEGAL_REPORT_PATH = ROOT / "audit" / "legal_report.md"

LEGAL_REPORT_SKELETON = """\
# Legal report skeleton: MaskPersona AI release audit

> Auto-generated by `audit/run_audits.py`. Fill in the sections below after running the
> `audit/legal_lawyer_agent.md` audit in-session. This file is gitignored (runtime artifact).

## 1. GDPR / data-protection posture
- Biometric voice fingerprint: lawful basis assessed? [ ]
- DPIA required and planned? [ ]
- Transparency/notice obligations to data subjects considered? [ ]
- Retention/deletion schedule documented? [ ]

## 2. Publicity and personality rights
- Public-figure gate confirmed? [ ]
- No impersonation / endorsed=false enforced? [ ]
- Post-mortem rights checked for the target figure? [ ]

## 3. Open-source license compliance
- All dependency licenses reviewed against MIT? [ ]
- No bundled third-party copyrighted content? [ ]
- Model-weight licenses reviewed? [ ]

## 4. Genericity / no real-person data
- Genericity audit PASS? [ ]
- Text-classifier audit PASS? [ ]
- grep for real-person/owner/machine traces: zero? [ ]

## 5. Decision
- [ ] RELEASE BLOCKED (list reasons below)
- [ ] RELEASE APPROVED

Notes:
"""


def run_audits() -> dict:
    LEGAL_REPORT_PATH.write_text(LEGAL_REPORT_SKELETON, encoding="utf-8")
    return {
        "agent_audits_to_dispatch": AGENT_AUDITS,
        "legal_report": str(LEGAL_REPORT_PATH.relative_to(ROOT)),
    }


def main() -> int:
    r = run_audits()
    print("Dispatch the following Opus AI audits in parallel (in-session):")
    for a in r["agent_audits_to_dispatch"]:
        print(f"  - {a}")
    print(f"\nLegal report skeleton written to: {r['legal_report']}")
    print("Review each audit output, fill in the skeleton, then confirm RELEASE APPROVED.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
